services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ecomdb
      POSTGRES_PASSWORD: ecom123
      POSTGRES_DB: nextecom
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
