services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: nextecomuser
      POSTGRES_PASSWORD: nextecom1234
      POSTGRES_DB: nextecom
    ports:
      - '5434:5434'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
